### ISSUE TITLE
Just released 1.2.2

### ISSUE THREAD

**Issue by baconpaul** [flathub/org.surge_synth_team.surge-xt#11]
@hfiguiere just fyi we released 1.2.2 today (after 1.2.1 last night - sigh. Sometimes you miss one thing)

It fixes a couple of important things for linux users so wanted to flag it to you.

**Comment by hfiguiere** [comment]
I saw. 

I had 1.2.1 ready to go. Later tonight for 1.2.2

**Comment by baconpaul** [comment]
Thanks! And yeah one stupid bug in 1.2.1 - sigh. Sorry

**Comment by hfiguiere** [comment]
no worries. I just follow but I needed to test the build so it wasn't merged
