### ISSUE TITLE
Surge User Interface Faulty

### ISSUE THREAD

**Issue by Basherbish330** [flathub/org.surge_synth_team.surge-xt#16]
Surge GUI fault/bug.
single./split/dual mode selector is on top of A B scene selector obscuring most of scene select **B** tab.
It is still possible to select scene B but is  fiddly and obviously faulty GUI.

Filter 2 is white and blank with no cut off or resonance sliders.
If I open the filter window for editing as soon as I try to move the cut off of filter 2, Reaper crashes every time!

Using latest version of Reaper on windows 10 64 bit.

**Comment by Basherbish330** [comment]
Tried reinstalling several times but Surge XT still manifesting the same issue.
Is a wonderful synth though and best  free synth.
Very in depth modulation possibilities that rival those of modular systems !  :-D

**Comment by hfiguiere** [comment]
this is not Surge-XT bug tracker.

**Comment by Basherbish330** [comment]
Ok so where do I go for help?

**Comment by baconpaul** [comment]
Surge has its own bug tracker on the surge GitHub

but the answer to your question is: somehow your install has skin files for an older version of surge than the version you are running. If you use custom skins redownload them and if you don’t your install didn’t install the data bundle properly for whatever mechanism you are using

**Comment by Basherbish330** [comment]
Thanks Paul for your reply.I haven't downloaded any skins or used any other than the default and dark skins.I have tried to find anything on GitHub but couldn't find a way of posting my query.Filter 2 select window is blank and I was unable to edit it in any way except choosing from the several presets available with the orange number box to the right.The single/split/dual options are obscuring the scene select A & B buttons and I have tried reinstalling Surge several times in case there was an error.
Kind regards,
Jules    On Saturday, 16 December 2023 at 14:11:47 GMT, Paul ***@***.***> wrote:  
 
 


Surge has its own bug tracker on the surge GitHub

but the answer to your question is: somehow your install has skin files for an older version of surge than the version you are running. If you use custom skins redownload them and if you don’t your install didn’t install the data bundle properly for whatever mechanism you are using
